name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses
      - name: Install SDK components
        run: sdkmanager "platforms;android-33" "build-tools;33.0.2"  # Adjust to your compileSdk and buildToolsVersion
      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build with Gradle
        run: ./gradlew build --info --stacktrace
