name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: List Available Tasks (Debug)
        run: ./gradlew tasks --all  # Lista todas las tareas para verificar si :app:assembleDebug existe
      - name: Build APK Debug
        run: ./gradlew :app:assembleDebug --stacktrace --info  # Agrega flags para más detalles en logs
      - name: Build APK Release
        run: ./gradlew :app:assembleRelease --stacktrace --info  # Agrega flags para más detalles en logs
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: sunday-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: sunday-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk